<?php $data = $this->getData();?>
 <!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title></title>

        <style>
            table{
                font-family: "Muli", "Helvetica Neue", "Arial", sans-serif;
                width:100%;
                border-collapse: collapse;
                table-layout:fixed;
                font-size: 12px;
            }
            th{
                text-align:center;
                border: 1px solid #A2A9B1;
                text-transform: uppercase;
                padding: 0.75rem;
                color: #2e3138;
                font-size: 12px;
            }
            td{
                text-align:center;
                color: #6c757d;
                border: 1px solid #A2A9B1;
                padding: 0.75rem;
                text-overflow: ellipsis !important;
                font-size: 12px;
            }
            .img{
                padding: 0.75rem;
                margin: 0 auto !important;
                display: block;
                margin-left: auto;
                margin-right: auto;
                width: 80%;
            }
            
        </style>
    </head>
<body>
 <div style="text-align: center">
  <img src="<?php echo $data['img'];?>" class="img">
</div>
<table class="table">
    <thead>
        <tr>
            <th colspan="2">IRA</th>
            <th colspan="2">Rollover</th>
            <th colspan="2">Savings</th>
            <th colspan="2">Annuity</th>
            <th colspan="2">Inheritance</th>
        </tr>
    </thead>
    <tbody>
    		<?php foreach($data['result'] as $key => $record):?>
				<tr>
					<td><?php echo $key;?></td>
					<td><?php echo $block->currencyFormat($record['ira']);?></td>
					<td><?php echo $key;?></td>
					<td><?php echo $block->currencyFormat($record['rollover']);?></td>
					<td><?php echo $key;?></td>
					<td><?php echo $block->currencyFormat($record['savings']);?></td>
					<td><?php echo $key;?></td>
					<td><?php echo $block->currencyFormat($record['annuity']);?></td>
					<td><?php echo $key;?></td>
					<td><?php echo $block->currencyFormat($record['inheritance']);?></td>
				</tr>
			<?php endforeach;?>
    </tbody>
</table>
</html>