<?php
	/**
	 * @var $block \Bdollarapps\ReportSystem\Block\Report\Default
	 */
?>

<?php
	$groupID = $block->getGroupId();
	$loggedInStatus = $block->getLoggedInStatus();
?>


<?php if($loggedInStatus && $groupID != 1): ?>
<!-- Start of bdollarsmarthelp Zendesk Widget script -->
<script id="ze-snippet" src="https://static.zdassets.com/ekr/snippet.js?key=1f46858f-1d27-4d7c-954f-d55f378fc35a"> </script>
<!-- End of bdollarsmarthelp Zendesk Widget script -->
<?php endif; ?>