<?php $currentAgent = $block->getCurrentAgent(); ?>
<?php if($block->getGroupId() != 1): ?>
<?php $list = $this->getAgentList();?>
<?php endif; ?>
<?php $result = $this->getSurveyCollection();?>
<?php $result->getSelect()->group('initials');?>

<?php 
$custId = $block->getCustomerId();
$level2 = "null";
$fullAccess = "null";

// if RVP - show securities document
if($block->getGroupId() != 1){
	$doc_acc = "sl";
}
// if Agent - show license approved by RVP
if($block->getGroupId() == 1 && $block->getLifeLicense($custId)){
	$doc_acc = "llo";
}
if($block->getGroupId() == 1 && $block->getSecurityLicense($custId)){
	$doc_acc = "sl";
}

if($block->getGroupId() == 1 && $block->getLevel1Access($custId)){
	$level1 = "level-1";
}else{
	$level1 = "null";
}

if($block->getGroupId() == 1 && $block->getLevel2Access($custId)){
	$level2 = "level-2";
}else{
	$level2 = "null";
}

if($block->getGroupId() == 1 && $block->getFullAccess($custId)){
	$fullAccess = "full-access";
}else{
	$fullAccess = "null";
}

$lang = $this->getRequest()->getParam('lang'); 

if(!empty($lang) && $lang == 'es'){
	$lang = 'es';
}else{
	$lang = 'en';
}

$docVersion = $this->getRequest()->getParam('doc_ver'); 

$access = $this->getRequest()->getParam('access');


?>
<!-- Welcome Alert -->

<div id="welcomeAlert">
    <div class="modal-body-content">
        <p><?= __('Please select the version you would like to practice with.') ?></p>
		<?php if($block->getGroupId() == 1 && !$block->getFullAccess($custId)):?>
			<p><?= __('Note: BDassist Practice version is based upon your training system access. if you dont have access to a sepcific version, please contact your RVP to unlock it for you.') ?></p>
		<?php endif; ?>
		<a href="/report/report/practicebdassist?access=<?= $level1 ?>"><?= __('Practice BDassist: Level 1') ?></a>
		<a href="/report/report/practicebdassist?access=<?= $level2 ?>"><?= __('Practice BDassist: Level 2') ?></a>
		<a href="/report/report/practicebdassist?access=<?= $fullAccess ?>"><?= __('Practice BDassist: Full Version') ?></a>
    </div>
</div>

<div class="row row-sm mt-5 toolset">
	<div class="col-lg-6">
		<h3 class="text-left">Practice BDassist</h3>
	</div>
	<div class="col-lg-6">
		<div class="toolbar">
			<!-- live bdassist -->
			<div id="live_bdassist" class="bassist">
				<a href="/report/report/bdassist" class="btn btn-primary">
					<?= __('LIVE BDASSIST'); ?>
				</a>
			</div>
			<!-- language switcher -->
			<div id="lang" class="lang-switcher">
				<?php if($lang == 'en'): ?>
					<a href="/report/report/practicebdassist?lang=es" class="btn btn-primary spanish">
						<?= __('VIEW SPANISH VERSION'); ?>
					</a>
				<?php else: ?>
					<a href="/report/report/practicebdassist?lang=en" class="btn btn-primary english">
						<?= __('VIEW ENGLISH VERSION'); ?>
					</a>
				<?php endif; ?>
			</div>
			<!-- font size -->
			<p class="font-size-label">Font Size</p>
			<div class="font-adjuster">
				<div class="controls">
					<button id="down" class="btn btn-primary">-</button>
					<p id="font-size"></p>
					<button id="up" class="btn btn-primary">+</button>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row row-sm mt-5">
<div class="col-lg-12">
	<div class="row">
		<div class="card col-md-2 surveyresult_console">
			<!-- View Survey Details Modal -->			
			<div class="modal fade" id="largemodal" tabindex="-1" role="dialog">
				<div class="modal-dialog modal-lg" role="document">
					<div class="modal-content">
						<div class="modal-header d-block">
							<h4 class="modal-title">Client Checkup Alerts</h4>
						</div>
						<div class="modal-body">						
							<div class="intro_trainee survey-alert <?= $level1 ? $level1:"" ?>">
								<h4 class="modal-title">Intro (Trainee Invloved)</h4>
							</div>

							<div class="intro_no_trainee survey-alert">
								<h4 class="modal-title">Intro (NO Trainee Invloved)</h4>
							</div>

							<div class="intro_to_a_referred_lead survey-alert">
								<h4 class="modal-title">Intro to a Referred Lead</h4>
							</div>

							<div class="no_will survey-alert <?= $level1 ? $level1:"" ?>">
								<h4 class="modal-title">No Will</h4>
							</div>

							<div class="update_your_will survey-alert">
								<h4 class="modal-title">Update Your Will</h4>
							</div>

							<div class="no_identity_theft_protection survey-alert <?= $level1 ? $level1:"" ?>">
								<h4 class="modal-title">No Identity Theft Protection</h4>
							</div>

							<div class="identity_theft_protection_confirm_best_value survey-alert <?= $level1 ? $level1:"" ?>">
								<h4 class="modal-title">Identity Theft Protection - Confirm best value</h4>
							</div>

							<div class="auto_home_comparison survey-alert <?= $level1 ? $level1:"" ?>">
								<h4 class="modal-title">Auto & Home comparison</h4>
							</div>

							<div class="warm_market_appointment_etting survey-alert <?= $level1 ? $level1:"" ?>">
								<h4 class="modal-title">Warm Market Appointment Setting</h4>
							</div>

							<div class="smart_home_security_system_confirm_the_best_value survey-alert">
								<h4 class="modal-title">Smart home security system - Confirm the best value</h4>
							</div>

							<div class="no_smart_home_security_system survey-alert">
								<h4 class="modal-title">No smart home security system</h4>
							</div>

							<div class="tax_filing_status survey-alert">
								<h4 class="modal-title">Tax filing status</h4>
							</div>

							<div class="upcoming_retirement_explore_moving_retirement_fund_to_an_ira survey-alert">
								<h4 class="modal-title">Upcoming retirement: Explore moving retirement fund to an IRA</h4>
							</div>

							<div class="educational_saving_account survey-alert">
								<h4 class="modal-title">Educational Savings Account</h4>
							</div>

							<div class="no_health_insurance survey-alert">
								<h4 class="modal-title">No health insurance</h4>
							</div>

							<div class="no_roth_ira survey-alert">
								<h4 class="modal-title">No Roth IRA</h4>
							</div>

							<div class="roth_ira_confirm_appropriate_allocation survey-alert">
								<h4 class="modal-title">Roth IRA - Confirm appropriate allocation</h4>
							</div>

							<div class="you_may_be_underfunding_your_roth_ira survey-alert">
								<h4 class="modal-title">You may be Underfunding your Roth IRA</h4>
							</div>

							<div class="you_may_be_overfunding_your_roth_ira survey-alert">
								<h4 class="modal-title">You may be Overfunding your Roth IRA</h4>
							</div>

							<div class="traditional_ira_confirm_appropriate_allocation survey-alert">
								<h4 class="modal-title">Traditional IRA - Confirm appropriate allocation</h4>
							</div>

							<div class="you_may_be_underfunding_your_traditional_ira survey-alert">
								<h4 class="modal-title">You may be Underfunding your Traditional IRA</h4>
							</div>

							<div class="you_may_be_overfunding_your_traditional_ira survey-alert">
								<h4 class="modal-title">You may be Overfunding your Traditional IRA</h4>
							</div>

							<div class="you_may_be_underfunding_your_roth_or_traditional_ira survey-alert">
								<h4 class="modal-title">You may be Underfunding your Roth or Traditional IRA</h4>
							</div>

							<div class="you_may_be_overfunding_your_roth_or_traditional_ira survey-alert">
								<h4 class="modal-title">You may be Overfunding your Roth or Traditional IRA</h4>
							</div>

							<div class="consider_a_rollover survey-alert">
								<h4 class="modal-title">Consider a Rollover</h4>
							</div>

							<div class="in_service_distribution survey-alert">
								<h4 class="modal-title">In-Service Distribution</h4>
							</div>

							<div class="required_minimum_distributions survey-alert">
								<h4 class="modal-title">Required Minimum Distributions</h4>
							</div>

							<div class="upcoming_inheritance survey-alert">
								<h4 class="modal-title">Upcoming Inheritance</h4>
							</div>

							<div class="inheritance survey-alert">
								<h4 class="modal-title">Inheritance</h4>
							</div>

							<div class="tax_refund survey-alert">
								<h4 class="modal-title">Tax refund</h4>
							</div>

							<div class="no_work_sponsored_retirement_plan_in_place survey-alert">
								<h4 class="modal-title">No work-sponsored retirement plan in place</h4>
							</div>

							<div class="401k_not_contributing survey-alert">
								<h4 class="modal-title">401(K) Not Contributing</h4>
							</div>

							<div class="401k_under_contributing_for_employer_match survey-alert">
								<h4 class="modal-title">401(k) Under Contributing for Employer Match</h4>
							</div>

							<div class="explore_the_options_of_a_sep_simple_or_solo_401k_retirement_plan survey-alert">
								<h4 class="modal-title">Explore the options of a SEP, SIMPLE or Solo 401K Retirement plan</h4>
							</div>

							<div class="explore_the_options_of_a_simple_retirement_plan survey-alert">
								<h4 class="modal-title">Explore the options of a SIMPLE Retirement Plan</h4>
							</div>

							<div class="explore_the_options_of_a_401k_retirement_plan survey-alert">
								<h4 class="modal-title">Explore the options of a 401K Retirement Plan</h4>
							</div>

							<div class="fiduciary_you_may_be_personally_legally_liable survey-alert">
								<h4 class="modal-title">Fiduciary-You may be personally legally liable</h4>
							</div>

							<div class="potentially_paying_high_fees_on_your_401k_plan survey-alert">
								<h4 class="modal-title">Potentially paying high fees on your 401(k) Plan</h4>
							</div>

							<div class="financial_wellness_seminar_to_increase_401k_participation survey-alert">
								<h4 class="modal-title">Financial Wellness Seminar To Increase 401K Participation</h4>
							</div>

							<div class="buy_sell_insurance survey-alert">
								<h4 class="modal-title">Buy-Sell Insurance</h4>
							</div>

							<div class="consider_debt_consolidation survey-alert">
								<h4 class="modal-title">Consider a debt consolidation</h4>
							</div>

							<div class="new_home_finance survey-alert">
								<h4 class="modal-title">New Home finance</h4>
							</div>

							<div class="second_home_finance survey-alert">
								<h4 class="modal-title">Second home finance</h4>
							</div>

							<div class="debt_elimination_plan survey-alert">
								<h4 class="modal-title">Debt Elimination Plan</h4>
							</div>

							<div class="cd_explore_options_with_higher_rate_of_return survey-alert">
								<h4 class="modal-title">CD: Explore options with higher rate of return</h4>
							</div>

							<div class="annuities_may_annuitize survey-alert">
								<h4 class="modal-title">Annuities may annuitize</h4>
							</div>

							<div class="savings_account survey-alert">
								<h4 class="modal-title">Savings Account</h4>
							</div>

							<div class="no_life_insurance survey-alert <?= $level2 ? $level2:"" ?>">
								<h4 class="modal-title">No Life Insurance</h4>
							</div>

							<div class="you_may_be_underinsured survey-alert <?= $level2 ? $level2:"" ?>">
								<h4 class="modal-title">You may be Underinsured</h4>
							</div>

							<div class="self_term_life_insurance_confirm_best_value survey-alert">
								<h4 class="modal-title">Term Life Insurance - Confirm the Best Value</h4>
							</div>

							<div class="insurance_with_saving_account survey-alert <?= $level2 ? $level2:"" ?>">
								<h4 class="modal-title">Insurance with saving account</h4>
							</div>

							<div class="group_life_insurance survey-alert <?= $level2 ? $level2:"" ?>">
								<h4 class="modal-title">Group Life Insurance</h4>
							</div>

							<div class="beneficiary_update survey-alert">
								<h4 class="modal-title">Beneficiary update</h4>
							</div>

							<div class="increase_my_income survey-alert <?= $level2 ? $level2:"" ?>">
								<h4 class="modal-title">Increase my income: $<span class="increase_my_income_value"></span></h4>
							</div>

							<div class="summary_close_priorities survey-alert <?= $level2 ? $level2:"" ?>">
								<h4 class="modal-title">Summary Close/Priorities</h4>
							</div>

							<div class="securing_introductions_referrals survey-alert <?= $level2 ? $level2:"" ?>">
								<h4 class="modal-title">Securing Introductions (referrals)</h4>
							</div>

						</div>
						<div class="modal-footer p-0">
						</div>
					</div>
				</div>
			</div>
			<!-- End Modal -->
		</div>
		
		<div class="card col-md-6 document_console">
			<div id="docPanel" class="document-panel">
				<span class="doc-notice"> Please select an client checkup alert from the left pane to load load the document here.</span>
				<div class="intro_trainee alert-doc <?= $level1 ? $level1:"" ?>">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_intro_trainee_involved')->toHtml();?>
				</div>
				<div class="intro_no_trainee alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_intro_no_trainee_involved')->toHtml();?>
				</div>
				
				<div class="intro_to_a_referred_lead alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_intro_to_a_referred_lead')->toHtml();?>
				</div>
				<div class="no_will alert-doc <?= $level1 ? $level1:"" ?>">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_no_will')->toHtml();?>
				</div>

				<div class="update_your_will alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_update_your_will')->toHtml();?>

				</div>

				<div class="no_identity_theft_protection alert-doc <?= $level1 ? $level1:"" ?>">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_no_identity_theft_protection')->toHtml();?>

				</div>

				<div class="identity_theft_protection_confirm_best_value alert-doc <?= $level1 ? $level1:"" ?>">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_id_theft_confirm_the_best_value')->toHtml();?>

				</div>

				<div class="auto_home_comparison alert-doc <?= $level1 ? $level1:"" ?>">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_auto_home_comparison')->toHtml();?>

				</div>

				<div class="warm_market_appointment_etting alert-doc <?= $level1 ? $level1:"" ?>">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_warm_market_appointment_etting')->toHtml();?>

				</div>

				<div class="smart_home_security_system_confirm_the_best_value alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_smart_home_security_system_confirm_the_best_value')->toHtml();?>

				</div>

				<div class="no_smart_home_security_system alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_no_smart_home_security_system')->toHtml();?>

				</div>

				<div class="tax_filing_status alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_tax_filing_status')->toHtml();?>

				</div>

				<div class="upcoming_retirement_explore_moving_retirement_fund_to_an_ira alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_upcoming_retirement_explore_moving_retirement_fund_to_an_ira')->toHtml();?>

				</div>

				<div class="educational_saving_account alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_educational_saving_account')->toHtml();?>

				</div>

				<div class="no_health_insurance alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_no_health_insurance')->toHtml();?>

				</div>

				<div class="no_roth_ira alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_no_roth_ira')->toHtml();?>

				</div>

				<div class="roth_ira_confirm_appropriate_allocation alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_roth_ira_confirm_appropriate_allocation')->toHtml();?>

				</div>

				<div class="you_may_be_underfunding_your_roth_ira alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_you_may_be_underfunding_your_roth_ira')->toHtml();?>

				</div>

				<div class="you_may_be_overfunding_your_roth_ira alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_you_may_be_overfunding_your_roth_ira')->toHtml();?>

				</div>

				<div class="traditional_ira_confirm_appropriate_allocation alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_traditional_ira_confirm_appropriate_allocation')->toHtml();?>

				</div>

				<div class="you_may_be_underfunding_your_traditional_ira alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_you_may_be_underfunding_your_traditional_ira')->toHtml();?>

				</div>

				<div class="you_may_be_overfunding_your_traditional_ira alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_you_may_be_overfunding_your_traditional_ira')->toHtml();?>

				</div>

				<div class="you_may_be_underfunding_your_roth_or_traditional_ira alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_you_may_be_underfunding_your_roth_or_traditional_ira')->toHtml();?>

				</div>

				<div class="you_may_be_overfunding_your_roth_or_traditional_ira alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_you_may_be_overfunding_your_roth_or_traditional_ira')->toHtml();?>

				</div>

				<div class="consider_a_rollover alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_consider_a_rollover')->toHtml();?>

				</div>

				<div class="in_service_distribution alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_in_service_distribution')->toHtml();?>

				</div>

				<div class="required_minimum_distributions alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_required_minimum_distributions')->toHtml();?>

				</div>

				<div class="upcoming_inheritance alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_upcoming_inheritance')->toHtml();?>

				</div>

				<div class="inheritance alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_inheritance')->toHtml();?>

				</div>

				<div class="tax_refund alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_tax_refund')->toHtml();?>

				</div>

				<div class="no_work_sponsored_retirement_plan_in_place alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_no_work_sponsored_retirement_plan_in_place')->toHtml();?>

				</div>

				<div class="401k_not_contributing alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_401k_not_contributing')->toHtml();?>

				</div>

				<div class="401k_under_contributing_for_employer_match alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_401k_under_contributing_for_employer_match')->toHtml();?>

				</div>

				<div class="explore_the_options_of_a_sep_simple_or_solo_401k_retirement_plan alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_explore_sep_simple_or_solo_401k')->toHtml();?>

				</div>

				<div class="explore_the_options_of_a_simple_retirement_plan alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_explore_the_options_of_a_simple_retirement_plan')->toHtml();?>

				</div>

				<div class="explore_the_options_of_a_401k_retirement_plan alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_explore_the_options_of_a_simple_retirement_plan')->toHtml();?>

				</div>

				<div class="fiduciary_you_may_be_personally_legally_liable alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_fiduciary_you_may_be_personally_legally_liable')->toHtml();?>

				</div>

				<div class="potentially_paying_high_fees_on_your_401k_plan alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_potentially_paying_high_fees_on_your_401k_plan')->toHtml();?>

				</div>

				<div class="financial_wellness_seminar_to_increase_401k_participation alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_financial_wellness_seminar_to_increase_401k_participation')->toHtml();?>

				</div>

				<div class="buy_sell_insurance alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_buy_sell_insurance')->toHtml();?>

				</div>

				<div class="consider_debt_consolidation alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_consider_debt_consolidation')->toHtml();?>

				</div>

				<div class="new_home_finance alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_new_home_finance')->toHtml();?>

				</div>

				<div class="second_home_finance alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_second_home_finance')->toHtml();?>

				</div>

				<div class="debt_elimination_plan alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_debt_elimination_plan')->toHtml();?>

				</div>

				<div class="cd_explore_options_with_higher_rate_of_return alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_cd_explore_options_with_higher_rate_of_return')->toHtml();?>

				</div>

				<div class="annuities_may_annuitize alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_annuities_may_annuitize')->toHtml();?>

				</div>

				<div class="savings_account alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_savings_account')->toHtml();?>

				</div>

				<div class="no_life_insurance alert-doc <?= $level2 ? $level2:"" ?>">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_no_life_insurance')->toHtml();?>

				</div>

				<div class="you_may_be_underinsured alert-doc <?= $level2 ? $level2:"" ?>">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_you_may_be_underinsured')->toHtml();?>
				</div>

				<div class="self_term_life_insurance_confirm_best_value alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_self_term_life_insurance_confirm_best_value')->toHtml();?>

				</div>

				<div class="insurance_with_saving_account alert-doc <?= $level2 ? $level2:"" ?>">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_insurance_with_saving_account')->toHtml();?>

				</div>

				<div class="group_life_insurance alert-doc <?= $level2 ? $level2:"" ?>">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_group_life_insurance')->toHtml();?>

				</div>

				<div class="beneficiary_update alert-doc">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_beneficiary_update')->toHtml();?>

				</div>

				<div class="increase_my_income alert-doc <?= $level2 ? $level2:"" ?>">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_increase_my_income')->toHtml();?>
				</div>

				<div class="summary_close_priorities alert-doc <?= $level2 ? $level2:"" ?>">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_summary_close_priorities')->toHtml();?>
				</div>

				<div class="securing_introductions_referrals alert-doc <?= $level2 ? $level2:"" ?>">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($lang.'_'.$doc_acc.'_securing_introductions_referrals')->toHtml();?>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
<!-- End Row -->




<script>
    require([
        'jquery',
		'Magento_Ui/js/modal/modal',
        'domReady!'
    ], function($, modal){
        $(document).ready(function() {
			
			function getSize() {
				size = $( ".alert-doc" ).css( "font-size" );
				size = parseInt(size, 10);
				$( "#font-size" ).text(  size  );
			}

			//get inital font size
			getSize();

			$( "#up" ).on( "click", function() {
				// parse font size, if less than 50 increase font size
				if ((size + 2) <= 50) {
					$( ".alert-doc" ).css( "font-size", "+=2" );
					$( ".alert-doc h1" ).css( "font-size", "+=2" );
					$( ".alert-doc h2" ).css( "font-size", "+=2" );
					$( ".alert-doc h3" ).css( "font-size", "+=2" );
					$( ".alert-doc h4" ).css( "font-size", "+=2" );
					$( ".alert-doc h5" ).css( "font-size", "+=2" );
					$( ".alert-doc h6" ).css( "font-size", "+=2" );
					$( ".alert-doc p" ).css( "font-size", "+=2" );
					$( ".alert-doc span" ).css( "font-size", "+=2" );
					$( ".alert-doc b" ).css( "font-size", "+=2" );
					$( ".alert-doc strong" ).css( "font-size", "+=2" );
					$( ".alert-doc a" ).css( "font-size", "+=2" );
					$( ".alert-doc ul" ).css( "font-size", "+=2" );
					$( ".alert-doc li" ).css( "font-size", "+=2" );
					$( "#font-size" ).text(  size += 2 );
				}
			});

			$( "#down" ).on( "click", function() {
				if ((size - 2) >= 12) {
					$( ".alert-doc" ).css( "font-size", "-=2" );
					$( ".alert-doc h1" ).css( "font-size", "-=2" );
					$( ".alert-doc h2" ).css( "font-size", "-=2" );
					$( ".alert-doc h3" ).css( "font-size", "-=2" );
					$( ".alert-doc h4" ).css( "font-size", "-=2" );
					$( ".alert-doc h5" ).css( "font-size", "-=2" );
					$( ".alert-doc h6" ).css( "font-size", "-=2" );
					$( ".alert-doc p" ).css( "font-size", "-=2" );
					$( ".alert-doc span" ).css( "font-size", "-=2" );
					$( ".alert-doc b" ).css( "font-size", "-=2" );
					$( ".alert-doc strong" ).css( "font-size", "-=2" );
					$( ".alert-doc a" ).css( "font-size", "-=2" );
					$( ".alert-doc ul" ).css( "font-size", "-=2" );
					$( ".alert-doc li" ).css( "font-size", "-=2" );
					$( "#font-size" ).text(  size -= 2  );
				}
			});

			$("#details_0").trigger("click");

			var options = {
				type: 'popup',
				responsive: true,
				title: 'Welcome to Practice BDassist!'
			};

			var popup = modal(options, $('#welcomeAlert'));
			$('#welcomeAlert').modal('openModal');
			$("#close-popup").on('click', function(event){
				$("#welcomeAlert").modal("closeModal");     
			});

        });
		
		// loading bdassisst document panel
		$('.alert-doc').hide();
		$('.doc-notice').show();

		$(".surveyresult_console .survey-alert").on('click', (function (e) {
			var className = $(this).attr("class").split(' ')[0];
			console.log(className);
			$('.alert-doc').hide();
			$(".document_console ." + className).show();
			$('.doc-notice').hide();
		}));
		
    })


</script>

<style>
	html, body{
		font-size: 18px !important;
	}
	.report-report-practicebdassist.width1200 .page-main > .columns {
		max-width: 100%;
	}
	.questions {
	    margin-top: 15px;
	    padding-bottom: 15px;
	    border-bottom: 1px solid #eaedf1;
	    display: none;
	}
	.modal-body {
    	height: 50vh !important;
		width: 100% !important;
    	overflow-y: auto !important;
	}
	.modal-footer{
		display:none;
	}
	.col-md-3 {
	    flex: 0 0 25%;
	    max-width: 25%;
	}
	.col-md-9 {
	    flex: 0 0 75%;
	    max-width: 75%;
	}
	.row {
	    display: flex;
	    flex-wrap: wrap;
	}
	.col-lg-12 {
	    flex: 0 0 100%;
	    max-width: 100%;
	}
	.text-white {
	    color: #fff!important;
	}
	.text-center {
    	text-align: center!important;
	}
	.card-body {
	    padding: 15px 25px !important;
	}
	.bg-white {
	    background-color: #fff!important;
		padding: 10px;
	}
	.media {
	    align-items: flex-start;
	    display: flex;
	}
	.small, small {
	    font-size: 80%;
	    font-weight: 400;
	}

	.main {
		display: flex;
		flex-direction: column;
		justify-content: center;
		min-height: 100vh;
	}

	 h1{
	    color: inherit;
	    font-family: inherit;
	    font-weight: 400;
	    line-height: 1.1;
	    margin-bottom: 0.66em;
	}
	.card {
	    background-color: transparent !important;
	    border-bottom: 1px solid #fff !important;
	    border-radius: 0px !important;
	}
	.card {
	    margin-bottom: 0 !important;
	}
	.col-lg-6 {
	    flex: 0 0 50%;
	    max-width: 50%;
	}
	.bg-gray {
	    background: #5a6970!important;
	}
	.flex-wrap {
	    flex-wrap: wrap!important;
	}
	.row:last-child .card button {
		max-width: 195px;
		font-weight: 600;
	    font-size: 15px;
	}
	.btn-primary {
	    background: #6259ca!important;
	    border-color: #6a62cc!important;
	    color: #fff!important;
	}
	.d-flex { display:block; }
	div.survey-alert {
		width: 275px;
		border: 1px solid #eee;
		padding: 10px;
		border-radius: 5px;
		margin: 10px;
	}
	div.survey-alert h4.modal-title {
		text-align: left;
		font-size: 15px;
		white-space: nowrap;
		text-overflow: ellipsis;
		display: block;
		overflow: hidden;
		max-width: 230px;
	}
	.p-5.bg-gray.text-white {
		padding: 0px 5px;
	}
	.pt-2.agent_list {
		padding: 0px 5px;
		display: flex;
		flex-direction: column;
	}
	.agent_list .agents a strong, .agent_list .agents a {
		font-size: 18px;
		text-transform: uppercase;
		font-weight: normal !important;
		font-family: 'Calibri Regular';
	}
	.dt-buttons.btn-group{
		padding: 0px !important;
	}
	.search {
		margin: 0px 0px 20px;
		display: block;
		width: 100%;
	}
	.modal-popup .modal-title{
		border-bottom: none;
	}
	#priorityPanel {
		display: flex;
		flex-direction: column;
	}
	.survey-alert{
		display:none !important;
	}
	.alert-doc{
		display:none;
	}
	.view_details {
		border: 1px solid #eee;
		padding: 5px;
		margin-bottom: 0px;
		border-radius: 2px;
	}
	.card.col-md-2.client-console {
		background: #eee !important;
		margin-top: 20px;
	}
	.card.col-md-2.surveyresult_console {
		margin-top: 130px;
	}
	.card.col-md-2.priority_console {
		padding: 118px 10px;
		margin-top: 20px;
		background: #eee !important;
	}
	.survey-alert, .view_details {
		cursor: pointer;
		transition: .3s;
	}
	.survey-alert:hover, .survey-alert.selected, .view_details:hover {
		background: #eee;
		color: #333;
		transition: .3s;
	}
	.card.col-md-6.document_console {
		margin-top: 20px;
		padding: 95px 10px;
		border: 1px solid #eee;
		min-width: 600px;
		width: 600px;
	}
	.priority_console input.survey-alert {
		margin: 19px;
	}
	.modal-body-content {
		display: flex;
		flex-direction: column;
	}
	span.doc-notice {
		background: #cfc;
		padding: 1px;
		font-size: 12px;
		font-weight: 500;
		border: 1px solid #cfcfcf;
		color: #333;
	}
	.toolset {
		display: flex;
		align-items: center;
		background: #eee;
		padding: 10px;
	}
	.toolbar {
		justify-content: space-evenly;
	}
	.font-adjuster {
		display: flex;
		flex-direction: column;
		align-content: center;
		flex-wrap: wrap;
		justify-content: center;
		align-items: center;
	}
	.font-adjuster .controls {
		display: flex;
		align-items: center;
		flex-direction: row;
	}
	p.font-size-label {
		line-height: inherit;
		font-size: 12px;
		margin-bottom: 0;
	}
	#font-size {
		margin: 0 auto;
		padding: 5px;
	}
</style>

<?php if($block->getGroupId() == 1 && $block->getLevel1Access($custId) && $access == "level-1"): ?>
<style>
	.survey-alert.level-1{
		display:block !important;
	}
</style>
<?php endif;?>

<?php if($block->getGroupId() == 1 && $block->getLevel2Access($custId) && $access == "level-2"): ?>
<style>
	.survey-alert.level-2{
		display:block !important;
	}
</style>
<?php endif;?>

<?php if($block->getGroupId() == 1 && $block->getFullAccess($custId) && $access == "full-access"): ?>
<style>
	.survey-alert{
		display:block !important;
	}
</style>
<?php endif;?>
<?php if($block->getGroupId() == 1 && $access == "null"): ?>
<style>
	.survey-alert, .intro_no_trainee.survey-alert, .intro_trainee.survey-alert{
		display:none !important;
	}
</style>
<?php endif;?>
<?php if($block->getGroupId() != 1): ?>
<style>
	.survey-alert{
		display:block !important;
	}
</style>
<?php endif;?>