<?php 
 $helper = $this->helper('Bdollarapps\LearningManagementSystem\Helper\Data');

?>
<?php if($helper->getActiveSubscription()):?>

<div class="content-block content-box-block">
    <div class="mgs-content-box box-vertical">
	    <div class="content-wrapper">
		    <h4>Level 2</h4>
		    <div class="content"><p>Demonstrate the ability to use the App</p>
				<div class="panel-block-row panel-block block98 col-tb-12 col-mb-12 text-center gradient-button">
					<div style="">
						<div class="content-block mgs-button-block button-center button-shadow">
							 <button class="level-2-button" onclick="setLocation('<?php echo $this->getUrl('lms/course/view',['id'=>7]);?>')" <?php if(!$helper->getQuickCourseFinish()):?> disabled <?php endif;?>>
			                    <span>Get Started</span>
			                </button>
						</div>
					</div>
				</div>
			</div>
	    </div>
    </div>
</div>
<?php endif; ?>