<div class="content-wrapper">
    <h4>Quick Start</h4>
    <div class="content"><p>Everything you need to know to get started quickly using Bdollar$mart!</p>
        <div class="panel-block-row panel-block block98 col-tb-12 col-mb-12 text-center gradient-button">
            <div style="">
                <div class="content-block mgs-button-block button-center button-shadow">
                    <button class="quick-start-button" onclick="setLocation('<?php echo $this->getUrl('lms/course/view',['id'=>5]);?>')">
                        <span>Get Started</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
